\set ON_ERROR_STOP on

begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pg_catalog;

select plan(50);

select has_table('public', 'access_grants', 'access_grants exists');
select is((select count(*) from pg_catalog.pg_attribute where attrelid = 'public.access_grants'::regclass and attnum > 0 and not attisdropped), 27::bigint, 'access_grants has the approved physical-column count');
select ok(to_regclass('public.platform_role_assignments_id_user_role_uk') is not null, 'platform-role composite binding support exists');
select is((select count(*) from pg_catalog.pg_constraint where conrelid = 'public.access_grants'::regclass and contype = 'f'), 8::bigint, 'access_grants has all restrictive profile, role-binding, and successor foreign keys');
select is((select pg_catalog.pg_get_constraintdef(oid) from pg_catalog.pg_constraint where conrelid = 'public.access_grants'::regclass and conname = 'access_grants_role_binding_fk'), 'FOREIGN KEY (platform_role_assignment_id, user_profile_id, role_code) REFERENCES platform_role_assignments(id, user_profile_id, role_code) ON DELETE RESTRICT', 'grant subject, assignment, and role code are one restrictive composite binding');
select is((select count(*) from pg_catalog.pg_index where indrelid = 'public.access_grants'::regclass), 6::bigint, 'access_grants has primary, two temporal exclusions, and approved lookup indexes');
select ok(to_regclass('public.access_grants_subject_interval_excl') is not null, 'subject half-open validity exclusion exists');
select ok(to_regclass('public.access_grants_role_assignment_interval_excl') is not null, 'role-assignment half-open validity exclusion exists');
select ok((select pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) from pg_catalog.pg_attrdef ad join pg_catalog.pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum where ad.adrelid = 'public.access_grants'::regclass and a.attname = 'id') ~ 'gen_random_uuid', 'access_grants uses the qualified database UUIDv4 default');
select ok(obj_description('public.access_grants'::regclass) ilike '%not Firebase authentication%', 'table comment preserves the authority boundary');
select is((select count(*) from public.access_grants), 0::bigint, 'migration creates no access rows');
select ok(to_regclass('internal.security_eligibility_assessments') is null, 'security eligibility assessments remain absent');
select ok(to_regprocedure('claim_security.current_privileged_actor()') is null, 'no privileged-actor resolver is created');
select ok(to_regclass('claim_security.reviewer_claim_queue') is null, 'no Reviewer private-read projection is created');

select ok(not has_table_privilege('public', 'public.access_grants', 'select'), 'PUBLIC cannot select access_grants');
select ok(not has_table_privilege('anon', 'public.access_grants', 'select'), 'anon cannot select access_grants');
select ok(not has_table_privilege('authenticated', 'public.access_grants', 'select'), 'authenticated cannot select access_grants');
select ok(not has_table_privilege('service_role', 'public.access_grants', 'select'), 'service_role cannot select access_grants');
select ok(not has_table_privilege('mujahiz_claim_runtime', 'public.access_grants', 'select'), 'mujahiz_claim_runtime receives no access-grants authority');
select ok(not exists (
  select 1 from pg_catalog.pg_class c
  cross join lateral pg_catalog.aclexplode(coalesce(c.relacl, pg_catalog.acldefault('r', c.relowner))) acl
  where c.oid = 'public.access_grants'::regclass
    and acl.grantee in (0, 'anon'::regrole::oid, 'authenticated'::regrole::oid, 'service_role'::regrole::oid, 'mujahiz_claim_runtime'::regrole::oid)
), 'PUBLIC and application/API roles receive no direct access_grants privileges');
select is((select relrowsecurity from pg_catalog.pg_class where oid = 'public.access_grants'::regclass), false, 'access_grants has no RLS enabled');
select is((select count(*) from pg_catalog.pg_policy where polrelid = 'public.access_grants'::regclass), 0::bigint, 'access_grants has no RLS policies');
select is((select count(*) from pg_catalog.pg_trigger where tgrelid = 'public.access_grants'::regclass and not tgisinternal), 0::bigint, 'access_grants has no trigger or runtime mutation path');

create temporary table access_grant_test_ids (name text primary key, id uuid not null) on commit drop;

with inserted as (
  insert into public.user_profiles (full_name, account_context)
  values
    ('Synthetic Access Owner Subject', 'buyer'),
    ('Synthetic Access Admin Subject', 'buyer'),
    ('Synthetic Access History Subject', 'buyer'),
    ('Synthetic Access Grantor', 'buyer'),
    ('Synthetic Access Reviewer', 'buyer'),
    ('Synthetic Access Bootstrap Subject', 'buyer'),
    ('Synthetic Access Wrong Subject', 'buyer')
  returning id, full_name
)
insert into access_grant_test_ids (name, id)
select case full_name
  when 'Synthetic Access Owner Subject' then 'owner_subject'
  when 'Synthetic Access Admin Subject' then 'admin_subject'
  when 'Synthetic Access History Subject' then 'history_subject'
  when 'Synthetic Access Grantor' then 'grantor'
  when 'Synthetic Access Reviewer' then 'reviewer'
  when 'Synthetic Access Bootstrap Subject' then 'bootstrap_subject'
  when 'Synthetic Access Wrong Subject' then 'wrong_subject'
end, id from inserted;

with inserted as (
  insert into public.platform_role_assignments (
    user_profile_id, role_code, valid_from, assignment_source_type, assignment_reason_code,
    authorization_policy_version, evidence_reference, assigned_by_user_profile_id,
    assignment_system_source
  ) values
    ((select id from access_grant_test_ids where name = 'owner_subject'), 'owner', timestamptz '2020-01-01 00:00:00+00', 'role_administration', 'synthetic_owner_role', 'platform_roles_v1', 'synthetic-owner-role', (select id from access_grant_test_ids where name = 'grantor'), null),
    ((select id from access_grant_test_ids where name = 'admin_subject'), 'admin', timestamptz '2020-01-01 00:00:00+00', 'role_administration', 'synthetic_admin_role', 'platform_roles_v1', 'synthetic-admin-role', (select id from access_grant_test_ids where name = 'grantor'), null),
    ((select id from access_grant_test_ids where name = 'history_subject'), 'owner', timestamptz '2020-01-01 00:00:00+00', 'role_administration', 'synthetic_history_role', 'platform_roles_v1', 'synthetic-history-role', (select id from access_grant_test_ids where name = 'grantor'), null),
    ((select id from access_grant_test_ids where name = 'bootstrap_subject'), 'owner', timestamptz '2020-01-01 00:00:00+00', 'bootstrap_manifest', 'synthetic_bootstrap_role', 'platform_roles_v1', 'synthetic-bootstrap-role', null, 'synthetic_bootstrap')
  returning id, user_profile_id
)
insert into access_grant_test_ids (name, id)
select case user_profile_id
  when (select id from access_grant_test_ids where name = 'owner_subject') then 'owner_role'
  when (select id from access_grant_test_ids where name = 'admin_subject') then 'admin_role'
  when (select id from access_grant_test_ids where name = 'history_subject') then 'history_role'
  when (select id from access_grant_test_ids where name = 'bootstrap_subject') then 'bootstrap_role'
end, id from inserted;

select lives_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', 'access_administration', 'synthetic_owner_grant', 'access_v1', 'synthetic-owner-evidence', (select id from access_grant_test_ids where name = 'grantor'), (select id from access_grant_test_ids where name = 'reviewer')) $$, 'active Owner access with no horizon is accepted');
select lives_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'admin_subject'), (select id from access_grant_test_ids where name = 'admin_role'), 'admin', timestamptz '2026-01-01 00:00:00+00', timestamptz '2026-06-30 00:00:00+00', 'access_administration', 'synthetic_admin_grant', 'access_v1', 'synthetic-admin-evidence', (select id from access_grant_test_ids where name = 'grantor'), (select id from access_grant_test_ids where name = 'reviewer')) $$, 'finite Admin access of exactly 180 calendar days is accepted');
select lives_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_status, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', 'revoked', timestamptz '2021-01-01 00:00:00+00', timestamptz '2021-02-01 00:00:00+00', 'legacy_reconciliation', 'synthetic_owner_history', 'access_v1', 'synthetic-owner-history', (select id from access_grant_test_ids where name = 'grantor'), 'synthetic_revoked', 'synthetic_reconciliation', timestamptz '2021-02-01 00:00:00+00') $$, 'terminal historical Owner shape with an end time is representable');

with inserted as (
  insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id)
  values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', timestamptz '2022-01-01 00:00:00+00', 'access_administration', 'synthetic_successor', 'access_v1', 'synthetic-successor', (select id from access_grant_test_ids where name = 'grantor'))
  returning id
)
insert into access_grant_test_ids (name, id) select 'successor_access', id from inserted;

select lives_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_status, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, terminal_reason_code, terminated_by_user_profile_id, terminated_at, superseding_access_grant_id) values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', 'superseded', timestamptz '2021-03-01 00:00:00+00', timestamptz '2021-04-01 00:00:00+00', 'access_administration', 'synthetic_superseded', 'access_v1', 'synthetic-superseded', (select id from access_grant_test_ids where name = 'grantor'), 'synthetic_superseded', (select id from access_grant_test_ids where name = 'grantor'), timestamptz '2021-04-01 00:00:00+00', (select id from access_grant_test_ids where name = 'successor_access')) $$, 'valid superseded lifecycle shape is accepted');

select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'admin_subject'), (select id from access_grant_test_ids where name = 'admin_role'), 'admin', timestamptz '2027-01-01 00:00:00+00', timestamptz '2027-07-01 00:00:01+00', 'access_administration', 'synthetic_long_admin', 'access_v1', 'synthetic-long-admin', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'Admin access longer than 180 calendar days is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'admin_subject'), (select id from access_grant_test_ids where name = 'admin_role'), 'admin', timestamptz '2027-01-01 00:00:00+00', 'access_administration', 'synthetic_open_admin', 'access_v1', 'synthetic-open-admin', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'Admin access without a finite horizon is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', pg_catalog.statement_timestamp() + interval '1 day', 'access_administration', 'synthetic_finite_owner', 'access_v1', 'synthetic-finite-owner', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'active Owner access with a finite horizon is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'wrong_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', 'access_administration', 'synthetic_wrong_subject', 'access_v1', 'synthetic-wrong-subject', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'wrong subject for a referenced role assignment is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'admin', pg_catalog.statement_timestamp() + interval '1 day', 'access_administration', 'synthetic_wrong_role', 'access_v1', 'synthetic-wrong-role', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'wrong role code for a referenced role assignment is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ('00000000-0000-0000-0000-000000000001', (select id from access_grant_test_ids where name = 'owner_role'), 'owner', 'access_administration', 'synthetic_missing_profile', 'access_v1', 'synthetic-missing-profile', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'nonexistent profile is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), '00000000-0000-0000-0000-000000000002', 'owner', 'access_administration', 'synthetic_missing_assignment', 'access_v1', 'synthetic-missing-assignment', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'nonexistent role assignment is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', 'access_administration', 'synthetic_duplicate_assignment', 'access_v1', 'synthetic-duplicate-assignment', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'duplicate effective role-assignment access is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', timestamptz '2022-06-01 00:00:00+00', 'access_administration', 'synthetic_subject_overlap', 'access_v1', 'synthetic-subject-overlap', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'overlapping effective subject access is rejected');
select lives_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_status, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', 'expired', timestamptz '2021-05-01 00:00:00+00', timestamptz '2021-06-01 00:00:00+00', 'legacy_reconciliation', 'synthetic_expired', 'access_v1', 'synthetic-expired', (select id from access_grant_test_ids where name = 'grantor'), 'synthetic_expired', 'synthetic_reconciliation', timestamptz '2021-06-01 00:00:00+00') $$, 'non-overlapping historical access intervals are permitted');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_status, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', 'revoked', timestamptz '2023-01-01 00:00:00+00', timestamptz '2023-02-01 00:00:00+00', 'access_administration', 'synthetic_partial_terminal', 'access_v1', 'synthetic-partial-terminal', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'partial terminal provenance is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_status, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at, superseding_access_grant_id) values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', 'revoked', timestamptz '2023-03-01 00:00:00+00', timestamptz '2023-04-01 00:00:00+00', 'access_administration', 'synthetic_invalid_successor', 'access_v1', 'synthetic-invalid-successor', (select id from access_grant_test_ids where name = 'grantor'), 'synthetic_revoked', 'synthetic_system', timestamptz '2023-04-01 00:00:00+00', (select id from access_grant_test_ids where name = 'successor_access')) $$, null, 'successor reference is rejected outside superseded lifecycle');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_status, valid_from, valid_until, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from access_grant_test_ids where name = 'history_subject'), (select id from access_grant_test_ids where name = 'history_role'), 'owner', 'expired', timestamptz '2023-05-01 00:00:00+00', timestamptz '2023-06-01 00:00:00+00', 'access_administration', 'synthetic_bad_timestamp', 'access_v1', 'synthetic-bad-timestamp', (select id from access_grant_test_ids where name = 'grantor'), 'synthetic_expired', 'synthetic_system', timestamptz '2023-05-15 00:00:00+00') $$, null, 'terminal timestamps cannot precede the terminal validity horizon');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', timestamptz '2028-01-01 00:00:00+00', 'access_administration', 'synthetic_self_review', 'access_v1', 'synthetic-self-review', (select id from access_grant_test_ids where name = 'grantor'), (select id from access_grant_test_ids where name = 'owner_subject')) $$, null, 'subject self-review is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', timestamptz '2028-02-01 00:00:00+00', 'access_administration', 'synthetic_grantor_review', 'access_v1', 'synthetic-grantor-review', (select id from access_grant_test_ids where name = 'grantor'), (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'grantor and reviewer must be distinct');
select lives_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, grant_system_source) values ((select id from access_grant_test_ids where name = 'bootstrap_subject'), (select id from access_grant_test_ids where name = 'bootstrap_role'), 'owner', timestamptz '2026-01-01 00:00:00+00', 'bootstrap_manifest', 'synthetic_bootstrap_grant', 'access_v1', 'synthetic-bootstrap-grant', 'synthetic_bootstrap') $$, 'bootstrap/system provenance shape is representable without a human grantor');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id, grant_system_source) values ((select id from access_grant_test_ids where name = 'bootstrap_subject'), (select id from access_grant_test_ids where name = 'bootstrap_role'), 'owner', timestamptz '2027-01-01 00:00:00+00', 'bootstrap_manifest', 'synthetic_bad_bootstrap', 'access_v1', 'synthetic-bad-bootstrap', (select id from access_grant_test_ids where name = 'grantor'), 'synthetic_bootstrap') $$, null, 'contradictory human and bootstrap/system provenance is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_purpose, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', 'trial', timestamptz '2029-01-01 00:00:00+00', 'access_administration', 'synthetic_bad_purpose', 'access_v1', 'synthetic-bad-purpose', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'unapproved purpose is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, access_status, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', 'renewing', timestamptz '2029-02-01 00:00:00+00', 'access_administration', 'synthetic_bad_status', 'access_v1', 'synthetic-bad-status', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'unapproved lifecycle status is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, record_version, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', timestamptz '2029-03-01 00:00:00+00', 0, 'access_administration', 'synthetic_bad_version', 'access_v1', 'synthetic-bad-version', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'record version below one is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', timestamptz '2029-04-01 00:00:00+00', 'unbounded_source', 'synthetic_bad_source', 'access_v1', 'synthetic-bad-source', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'unapproved source class is rejected');
select throws_ok($$ insert into public.access_grants (user_profile_id, platform_role_assignment_id, role_code, valid_from, grant_source_type, grant_reason_code, authorization_policy_version, evidence_reference, granted_by_user_profile_id) values ((select id from access_grant_test_ids where name = 'owner_subject'), (select id from access_grant_test_ids where name = 'owner_role'), 'owner', timestamptz '2029-05-01 00:00:00+00', 'access_administration', 'Bad-Code', 'access_v1', 'synthetic-bad-code', (select id from access_grant_test_ids where name = 'grantor')) $$, null, 'reason code format is bounded');

delete from public.access_grants;
select is((select count(*) from public.access_grants), 0::bigint, 'no access rows remain after focused synthetic cleanup');

select * from finish();

rollback;
