\set ON_ERROR_STOP on

begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pg_catalog;

select plan(55);

select has_table('internal', 'security_eligibility_assessments', 'security eligibility assessments exists in the internal schema');
select is((select count(*) from pg_catalog.pg_attribute where attrelid = 'internal.security_eligibility_assessments'::regclass and attnum > 0 and not attisdropped), 29::bigint, 'security eligibility assessments has the approved physical-column count');
select is((select count(*) from pg_catalog.pg_constraint where conrelid = 'internal.security_eligibility_assessments'::regclass and contype = 'f'), 7::bigint, 'security eligibility assessments has restrictive profile and successor foreign keys');
select is((select count(*) from pg_catalog.pg_index where indrelid = 'internal.security_eligibility_assessments'::regclass), 4::bigint, 'security eligibility assessments has primary, temporal exclusion, and approved lookup indexes');
select ok(to_regclass('internal.security_eligibility_assessments_subject_policy_coverage_interval_excl') is not null, 'subject policy and coverage half-open validity exclusion exists');
select ok((select pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) from pg_catalog.pg_attrdef ad join pg_catalog.pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum where ad.adrelid = 'internal.security_eligibility_assessments'::regclass and a.attname = 'id') ~ 'gen_random_uuid', 'security eligibility assessments uses the qualified database UUIDv4 default');
select ok(obj_description('internal.security_eligibility_assessments'::regclass) ilike '%not Firebase authentication%', 'table comment preserves the security authority boundary');
select is((select count(*) from internal.security_eligibility_assessments), 0::bigint, 'migration creates no security eligibility rows');
select has_table('public', 'access_grants', 'access grants remains present');
select ok(to_regprocedure('claim_security.current_privileged_actor()') is null, 'no privileged-actor resolver is created');
select ok(to_regclass('claim_security.reviewer_claim_queue') is null, 'no Reviewer private-read projection is created');

select ok(not has_table_privilege('public', 'internal.security_eligibility_assessments', 'select'), 'PUBLIC cannot select security assessments');
select ok(not has_table_privilege('anon', 'internal.security_eligibility_assessments', 'select'), 'anon cannot select security assessments');
select ok(not has_table_privilege('authenticated', 'internal.security_eligibility_assessments', 'select'), 'authenticated cannot select security assessments');
select ok(not has_table_privilege('service_role', 'internal.security_eligibility_assessments', 'select'), 'service_role cannot select security assessments');
select ok(not has_table_privilege('mujahiz_claim_runtime', 'internal.security_eligibility_assessments', 'select'), 'mujahiz_claim_runtime receives no security assessment authority');
select ok(not exists (
  select 1 from pg_catalog.pg_class c
  cross join lateral pg_catalog.aclexplode(coalesce(c.relacl, pg_catalog.acldefault('r', c.relowner))) acl
  where c.oid = 'internal.security_eligibility_assessments'::regclass
    and acl.grantee in (0, 'anon'::regrole::oid, 'authenticated'::regrole::oid, 'service_role'::regrole::oid, 'mujahiz_claim_runtime'::regrole::oid)
), 'PUBLIC and application/API roles receive no direct security assessment privileges');
select is((select relrowsecurity from pg_catalog.pg_class where oid = 'internal.security_eligibility_assessments'::regclass), false, 'security eligibility assessments has no RLS enabled');
select is((select count(*) from pg_catalog.pg_policy where polrelid = 'internal.security_eligibility_assessments'::regclass), 0::bigint, 'security eligibility assessments has no RLS policies');
select is((select count(*) from pg_catalog.pg_trigger where tgrelid = 'internal.security_eligibility_assessments'::regclass and not tgisinternal), 0::bigint, 'security eligibility assessments has no trigger or runtime mutation path');

create temporary table security_assessment_test_ids (name text primary key, id uuid not null) on commit drop;

with inserted as (
  insert into public.user_profiles (full_name, account_context)
  values
    ('Synthetic Security Subject', 'buyer'),
    ('Synthetic Security History Subject', 'buyer'),
    ('Synthetic Security Unrelated Subject', 'buyer'),
    ('Synthetic Security Actor', 'buyer'),
    ('Synthetic Security Reviewer', 'buyer'),
    ('Synthetic Security Bootstrap Subject', 'buyer'),
    ('Synthetic Security System Subject', 'buyer')
  returning id, full_name
)
insert into security_assessment_test_ids (name, id)
select case full_name
  when 'Synthetic Security Subject' then 'subject'
  when 'Synthetic Security History Subject' then 'history_subject'
  when 'Synthetic Security Unrelated Subject' then 'unrelated_subject'
  when 'Synthetic Security Actor' then 'actor'
  when 'Synthetic Security Reviewer' then 'reviewer'
  when 'Synthetic Security Bootstrap Subject' then 'bootstrap_subject'
  when 'Synthetic Security System Subject' then 'system_subject'
end, id from inserted;

select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'subject'), 'clear', 'complete_clear', 'security_administration', 'synthetic_complete_clear', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-clear', (select id from security_assessment_test_ids where name = 'actor'), (select id from security_assessment_test_ids where name = 'reviewer')) $$, 'ordinary human dual-control complete clear is representable');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'subject'), 'clear', 'explicit_deny', timestamptz '2030-01-01 00:00:00+00', 'security_administration', 'synthetic_bad_clear', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-bad-clear', (select id from security_assessment_test_ids where name = 'actor'), (select id from security_assessment_test_ids where name = 'reviewer')) $$, null, 'clear requires complete_clear');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'explicit_deny', timestamptz '2020-01-01 00:00:00+00', timestamptz '2020-02-01 00:00:00+00', 'resolved', 'security_administration', 'synthetic_explicit_deny', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-deny', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_resolved', 'synthetic_security', timestamptz '2020-02-01 00:00:00+00') $$, 'explicit deny is representable as deny');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'security_hold', timestamptz '2020-02-01 00:00:00+00', timestamptz '2020-03-01 00:00:00+00', 'expired', 'security_administration', 'synthetic_security_hold', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-hold', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_expired', 'synthetic_security', timestamptz '2020-03-01 00:00:00+00') $$, 'security hold is representable as deny');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'identity_quarantine', timestamptz '2020-03-01 00:00:00+00', timestamptz '2020-04-01 00:00:00+00', 'resolved', 'security_administration', 'synthetic_identity_quarantine', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-quarantine', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_resolved', 'synthetic_security', timestamptz '2020-04-01 00:00:00+00') $$, 'identity quarantine is representable as deny');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessment_system_source, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'unknown', 'reconciliation_required', timestamptz '2020-04-01 00:00:00+00', timestamptz '2020-05-01 00:00:00+00', 'resolved', 'trusted_security_system', 'synthetic_reconciliation', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-reconciliation', 'synthetic_system', 'synthetic_resolved', 'synthetic_system', timestamptz '2020-05-01 00:00:00+00') $$, 'reconciliation required is representable as unknown');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'reconciliation_required', timestamptz '2030-02-01 00:00:00+00', 'security_administration', 'synthetic_bad_deny', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-bad-deny', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'reconciliation required cannot be deny');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'unknown', 'complete_clear', timestamptz '2030-03-01 00:00:00+00', 'security_administration', 'synthetic_bad_unknown', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-bad-unknown', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'complete clear cannot be unknown');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'unknown_condition', timestamptz '2030-04-01 00:00:00+00', 'security_administration', 'synthetic_unknown_condition', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-unknown-condition', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'unknown condition code is rejected');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'permit', 'complete_clear', timestamptz '2030-05-01 00:00:00+00', 'security_administration', 'synthetic_unknown_result', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-unknown-result', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'unknown result code is rejected');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_scope, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'supplier_administration', 'deny', 'explicit_deny', timestamptz '2030-06-01 00:00:00+00', 'security_administration', 'synthetic_bad_scope', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-bad-scope', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'unapproved scope is rejected');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, record_version, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'explicit_deny', timestamptz '2030-07-01 00:00:00+00', 0, 'security_administration', 'synthetic_bad_version', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-bad-version', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'record version below one is rejected');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'explicit_deny', timestamptz '2030-08-01 00:00:00+00', 'security_administration', 'synthetic_bad_reference', 'security_v1', 'coverage_v1', 'min_v1', '', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'bounded evidence reference is required');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'unrelated_subject'), 'deny', 'explicit_deny', timestamptz '2021-01-01 00:00:00+00', timestamptz '2021-02-01 00:00:00+00', 'resolved', 'security_administration', 'synthetic_resolved', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-resolved', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_resolved', 'synthetic_security', timestamptz '2021-02-01 00:00:00+00') $$, 'resolved lifecycle shape is representable');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'unrelated_subject'), 'deny', 'security_hold', timestamptz '2021-02-01 00:00:00+00', timestamptz '2021-03-01 00:00:00+00', 'expired', 'security_administration', 'synthetic_expired', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-expired', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_expired', 'synthetic_security', timestamptz '2021-03-01 00:00:00+00') $$, 'expired lifecycle shape is representable');
with successor as (
  insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, reviewed_by_user_profile_id)
  values ((select id from security_assessment_test_ids where name = 'unrelated_subject'), 'clear', 'complete_clear', timestamptz '2021-04-01 00:00:00+00', 'security_administration', 'synthetic_successor', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-successor', (select id from security_assessment_test_ids where name = 'actor'), (select id from security_assessment_test_ids where name = 'reviewer'))
  returning id
)
insert into security_assessment_test_ids (name, id) select 'successor', id from successor;
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at, superseding_assessment_id) values ((select id from security_assessment_test_ids where name = 'unrelated_subject'), 'unknown', 'reconciliation_required', timestamptz '2021-03-01 00:00:00+00', timestamptz '2021-04-01 00:00:00+00', 'superseded', 'security_administration', 'synthetic_superseded', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-superseded', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_superseded', 'synthetic_security', timestamptz '2021-04-01 00:00:00+00', (select id from security_assessment_test_ids where name = 'successor')) $$, 'superseded lifecycle shape with successor is representable');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'deny', 'explicit_deny', timestamptz '2031-01-01 00:00:00+00', 'security_administration', 'synthetic_active_terminal', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-active-terminal', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_terminal') $$, null, 'active lifecycle cannot contain terminal provenance');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at, superseding_assessment_id) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'deny', 'explicit_deny', timestamptz '2031-02-01 00:00:00+00', timestamptz '2031-03-01 00:00:00+00', 'resolved', 'security_administration', 'synthetic_resolved_successor', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-resolved-successor', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_resolved', 'synthetic_security', timestamptz '2031-03-01 00:00:00+00', (select id from security_assessment_test_ids where name = 'successor')) $$, null, 'successor is rejected outside superseded lifecycle');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'deny', 'explicit_deny', timestamptz '2031-04-01 00:00:00+00', timestamptz '2031-05-01 00:00:00+00', 'superseded', 'security_administration', 'synthetic_missing_successor', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-missing-successor', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_superseded', 'synthetic_security', timestamptz '2031-05-01 00:00:00+00') $$, null, 'superseded lifecycle requires successor');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'deny', 'explicit_deny', timestamptz '2031-06-01 00:00:00+00', timestamptz '2031-07-01 00:00:00+00', 'expired', 'security_administration', 'synthetic_bad_timestamp', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-bad-timestamp', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_expired', 'synthetic_security', timestamptz '2031-06-15 00:00:00+00') $$, null, 'terminal timestamps cannot precede the terminal validity horizon');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'explicit_deny', timestamptz '2020-04-15 00:00:00+00', 'security_administration', 'synthetic_overlap', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-overlap', (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'overlapping assessments for the same subject policy and coverage boundary are rejected');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, valid_until, assessment_status, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, terminal_reason_code, terminal_system_source, terminated_at) values ((select id from security_assessment_test_ids where name = 'history_subject'), 'deny', 'explicit_deny', timestamptz '2020-05-01 00:00:00+00', timestamptz '2020-06-01 00:00:00+00', 'resolved', 'security_administration', 'synthetic_nonoverlap', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-nonoverlap', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_resolved', 'synthetic_security', timestamptz '2020-06-01 00:00:00+00') $$, 'non-overlapping history is permitted');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessment_system_source) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'deny', 'security_hold', timestamptz '2020-01-01 00:00:00+00', 'trusted_security_system', 'synthetic_system_hold', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-system-hold', 'synthetic_security_system') $$, 'trusted-system restrictive provenance shape is representable');
select lives_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessment_system_source) values ((select id from security_assessment_test_ids where name = 'bootstrap_subject'), 'clear', 'complete_clear', timestamptz '2020-01-01 00:00:00+00', 'bootstrap_manifest', 'synthetic_bootstrap_clear', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-bootstrap-clear', 'synthetic_bootstrap') $$, 'bootstrap complete clear is representable without a fabricated human actor');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessment_system_source) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'clear', 'complete_clear', timestamptz '2032-01-01 00:00:00+00', 'trusted_security_system', 'synthetic_system_clear', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-system-clear', 'synthetic_security_system') $$, null, 'trusted system clear is structurally rejected');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, assessment_system_source) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'deny', 'explicit_deny', timestamptz '2032-02-01 00:00:00+00', 'security_administration', 'synthetic_mixed_provenance', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-mixed-provenance', (select id from security_assessment_test_ids where name = 'actor'), 'synthetic_security_system') $$, null, 'contradictory human and system provenance is rejected');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'clear', 'complete_clear', timestamptz '2032-03-01 00:00:00+00', 'security_administration', 'synthetic_self_clear', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-self-clear', (select id from security_assessment_test_ids where name = 'system_subject'), (select id from security_assessment_test_ids where name = 'reviewer')) $$, null, 'human clear actor cannot be the subject');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'clear', 'complete_clear', timestamptz '2032-04-01 00:00:00+00', 'security_administration', 'synthetic_same_reviewer', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-same-reviewer', (select id from security_assessment_test_ids where name = 'actor'), (select id from security_assessment_test_ids where name = 'actor')) $$, null, 'human clear actor and reviewer must be distinct');
select throws_ok($$ insert into internal.security_eligibility_assessments (user_profile_id, assessment_result, condition_type, valid_from, assessment_source_type, assessment_reason_code, security_policy_version, required_coverage_version, evidence_minimization_version, evidence_reference, assessed_by_user_profile_id, reviewed_by_user_profile_id) values ((select id from security_assessment_test_ids where name = 'system_subject'), 'clear', 'complete_clear', timestamptz '2032-05-01 00:00:00+00', 'security_administration', 'synthetic_self_review', 'security_v1', 'coverage_v1', 'min_v1', 'synthetic-self-review', (select id from security_assessment_test_ids where name = 'actor'), (select id from security_assessment_test_ids where name = 'system_subject')) $$, null, 'human clear reviewer cannot be the subject');
select ok(not exists (select 1 from pg_catalog.pg_attribute where attrelid = 'internal.security_eligibility_assessments'::regclass and attnum > 0 and not attisdropped and atttypid = 'pg_catalog.jsonb'::regtype), 'security assessments contain no arbitrary JSON column');
select ok(not exists (select 1 from pg_catalog.pg_attribute where attrelid = 'internal.security_eligibility_assessments'::regclass and attnum > 0 and not attisdropped and attname in ('firebase_uid', 'provider_subject', 'email', 'phone', 'raw_payload', 'investigation_notes', 'claim_evidence')), 'security assessments contain no prohibited Firebase, provider, contact, payload, or evidence columns');
select is((select count(*) from public.access_grants), 0::bigint, 'access grants remains empty after synthetic security tests');
select is((select count(*) from pg_catalog.pg_policy where polrelid = 'public.supplier_ownership_claims'::regclass), 1::bigint, 'Claim policy count remains exactly one');
select is((select count(*) from pg_catalog.pg_policy where polrelid = 'public.supplier_ownership_claims'::regclass and (polcmd = 'a' or polcmd = 'w' or polcmd = 'd')), 0::bigint, 'Claim mutation policy count remains zero');

delete from internal.security_eligibility_assessments;
select is((select count(*) from internal.security_eligibility_assessments), 0::bigint, 'no security eligibility rows remain after focused synthetic cleanup');

select * from finish();

rollback;
