\set ON_ERROR_STOP on

begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pg_catalog;

select plan(51);

select has_table('public', 'supplier_ownership_claims', 'supplier_ownership_claims exists in public');
select is((select count(*) from pg_catalog.pg_attribute where attrelid = 'public.supplier_ownership_claims'::regclass and attnum > 0 and not attisdropped), 41::bigint, 'Claim aggregate has the approved physical-column count');
select is((select count(*) from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass), 28::bigint, 'Claim aggregate has the exact approved constraint count');
select is((select string_agg(a.attname || ':' || pg_catalog.format_type(a.atttypid, a.atttypmod) || ':' || a.attnotnull::text, ',' order by a.attnum) from pg_catalog.pg_attribute a where a.attrelid = 'public.supplier_ownership_claims'::regclass and a.attnum > 0 and not a.attisdropped), 'id:uuid:true,claimant_user_profile_id:uuid:true,supplier_profile_id:uuid:true,status:text:true,record_version:integer:true,submitted_at:timestamp with time zone:true,expires_at:timestamp with time zone:true,submitted_reason:text:true,claimant_snapshot_schema_version:text:true,claimant_snapshot:jsonb:true,submission_fingerprint_version:text:true,submission_fingerprint:text:true,evidence_schema_version:text:true,evidence_descriptors:jsonb:true,reviewer_user_profile_id:uuid:false,reviewer_assignment_version:integer:false,reviewer_assigned_at:timestamp with time zone:false,reviewer_assigned_by_user_profile_id:uuid:false,reviewer_assignment_source_code:text:false,reviewer_assignment_policy_version:text:false,decided_by_user_profile_id:uuid:false,decided_at:timestamp with time zone:false,decision_reason_code:text:false,evidence_verification_method_code:text:false,evidence_verification_version:text:false,evidence_verification_outcome_code:text:false,decision_authorization_policy_version:text:false,reviewer_notes:text:false,withdrawn_at:timestamp with time zone:false,withdrawn_by_user_profile_id:uuid:false,withdrawal_reason_code:text:false,expired_at:timestamp with time zone:false,expiry_system_source_code:text:false,expiry_policy_version:text:false,superseded_at:timestamp with time zone:false,supersession_reason_code:text:false,prior_claim_id:uuid:false,superseded_by_claim_id:uuid:false,resulting_supplier_ownership_id:uuid:false,created_at:timestamp with time zone:true,updated_at:timestamp with time zone:true', 'Claim aggregate columns, types, order, and nullability match the approved local contract');
select is((select string_agg(a.attname || '=' || pg_catalog.pg_get_expr(d.adbin, d.adrelid), '|' order by a.attnum) from pg_catalog.pg_attrdef d join pg_catalog.pg_attribute a on a.attrelid = d.adrelid and a.attnum = d.adnum where d.adrelid = 'public.supplier_ownership_claims'::regclass), 'id=gen_random_uuid()|status=''submitted''::text|record_version=1|submitted_at=statement_timestamp()|evidence_descriptors=''[]''::jsonb|created_at=statement_timestamp()|updated_at=statement_timestamp()', 'Claim aggregate defaults are limited to approved database-generated values');
select ok(exists (select 1 from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass and conname = 'supplier_ownership_claims_status_ck'), 'Claim lifecycle status is constrained');
select ok(exists (select 1 from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass and conname = 'supplier_ownership_claims_lifecycle_shape_ck'), 'Claim lifecycle combinations are constrained');
select ok(exists (select 1 from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass and conname = 'supplier_ownership_claims_reviewer_assignment_shape_ck'), 'reviewer assignment is structurally all-or-none');
select ok(exists (select 1 from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass and conname = 'supplier_ownership_claims_decision_shape_ck'), 'decision provenance is structurally all-or-none');
select ok(exists (select 1 from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass and conname = 'supplier_ownership_claims_evidence_descriptors_ck'), 'evidence descriptors have a bounded versioned aggregate constraint');
select ok(exists (select 1 from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass and conname = 'supplier_ownership_claims_expiry_order_ck'), 'expiry cannot precede submission');
select is((select count(*) from pg_catalog.pg_constraint where conrelid = 'public.supplier_ownership_claims'::regclass and contype = 'f'), 9::bigint, 'Claim aggregate has only the approved restrictive foreign keys');
select ok(to_regclass('public.supplier_ownership_claims_one_active_pair_uidx') is not null, 'active Claim pair uniqueness index exists');
select ok(to_regclass('public.supplier_ownership_claims_supplier_active_lock_idx') is not null, 'Supplier active-Claim lock index exists');
select ok(to_regclass('public.supplier_ownership_claims_reviewer_queue_idx') is not null, 'reviewer queue index exists');
select ok(to_regclass('public.supplier_ownership_claims_active_expiry_idx') is not null, 'active expiry index exists');
select ok((select pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) from pg_catalog.pg_attrdef ad join pg_catalog.pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum where ad.adrelid = 'public.supplier_ownership_claims'::regclass and a.attname = 'id') ~ 'gen_random_uuid', 'Claim identity uses the qualified database UUIDv4 default');
select ok(obj_description('public.supplier_ownership_claims'::regclass) ilike '%not a current ownership authority%', 'table comment preserves the empty local-only boundary');
select is((select count(*) from public.supplier_ownership_claims), 0::bigint, 'migration creates no Claim rows');
select is((select count(*) from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid = c.relnamespace where n.nspname in ('public', 'internal') and c.relkind = 'r'), 22::bigint, 'all migrations produce exactly 22 physical application tables');
select ok(to_regclass('public.supplier_ownership_claim_evidence') is null, 'no separate Claim evidence table is introduced');
select ok(to_regclass('public.supplier_claim_reviewer_assignments') is null, 'no reviewer-assignment table is introduced');
select ok(to_regclass('public.supplier_ownership_claim_events') is null, 'no Claim event/history table is introduced');
select ok(to_regclass('public.supplier_claim_rate_limits') is null, 'no Claim rate-limit table is introduced');
select ok(to_regclass('public.supplier_ownership_claim_attachments') is null, 'no Claim attachment table is introduced');
select ok(to_regclass('public.file_objects') is null, 'no file-object table is introduced');

select ok(not has_table_privilege('anon', 'public.supplier_ownership_claims', 'select'), 'anon cannot select Claims');
select ok(not has_table_privilege('authenticated', 'public.supplier_ownership_claims', 'select'), 'authenticated cannot select Claims');
select ok(not has_table_privilege('service_role', 'public.supplier_ownership_claims', 'select'), 'service API role cannot select Claims');
select ok(not exists (select 1 from pg_catalog.pg_class c cross join lateral pg_catalog.aclexplode(coalesce(c.relacl, pg_catalog.acldefault('r', c.relowner))) acl where c.oid = 'public.supplier_ownership_claims'::regclass and acl.grantee in (0, 'anon'::regrole::oid, 'authenticated'::regrole::oid, 'service_role'::regrole::oid)), 'PUBLIC and API roles receive no Claim privileges');
select is((select relrowsecurity from pg_catalog.pg_class where oid = 'public.supplier_ownership_claims'::regclass), false, 'Claim aggregate has no RLS enabled');
select is((select count(*) from pg_catalog.pg_policy where polrelid = 'public.supplier_ownership_claims'::regclass), 0::bigint, 'Claim aggregate has no policies');
select is((select count(*) from pg_catalog.pg_trigger where tgrelid = 'public.supplier_ownership_claims'::regclass and not tgisinternal), 0::bigint, 'Claim aggregate has no triggers');
select is((select count(*) from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid = p.pronamespace where n.nspname in ('public', 'internal') and p.proname in ('supplier_ownership_decide_claim', 'assign_supplier_claim_reviewer', 'expire_supplier_claim')), 0::bigint, 'slice introduces no Claim command or runtime function');

create temporary table claim_test_ids (name text primary key, id uuid not null) on commit drop;
with inserted as (insert into public.user_profiles (full_name, account_context) values ('Synthetic Claimant', 'supplier') returning id) insert into claim_test_ids select 'claimant', id from inserted;
with inserted as (insert into public.user_profiles (full_name, account_context) values ('Synthetic Reviewer', 'buyer') returning id) insert into claim_test_ids select 'reviewer', id from inserted;
with inserted as (insert into public.user_profiles (full_name, account_context) values ('Synthetic Assigner', 'buyer') returning id) insert into claim_test_ids select 'assigner', id from inserted;
with inserted as (insert into public.user_profiles (full_name, account_context) values ('Synthetic Other Claimant', 'supplier') returning id) insert into claim_test_ids select 'other_claimant', id from inserted;
with inserted as (insert into public.supplier_profiles (name_original, display_name, name_language, name_en, business_type, source_type, confidence_level, has_direct_experience) values ('Synthetic Claim Supplier One', 'Synthetic Claim Supplier One', 'english', 'Synthetic Claim Supplier One', 'company', 'other', 'low', 'no') returning id) insert into claim_test_ids select 'supplier_one', id from inserted;
with inserted as (insert into public.supplier_profiles (name_original, display_name, name_language, name_en, business_type, source_type, confidence_level, has_direct_experience) values ('Synthetic Claim Supplier Two', 'Synthetic Claim Supplier Two', 'english', 'Synthetic Claim Supplier Two', 'company', 'other', 'low', 'no') returning id) insert into claim_test_ids select 'supplier_two', id from inserted;
with inserted as (insert into public.supplier_profiles (name_original, display_name, name_language, name_en, business_type, source_type, confidence_level, has_direct_experience) values ('Synthetic Claim Supplier Three', 'Synthetic Claim Supplier Three', 'english', 'Synthetic Claim Supplier Three', 'company', 'other', 'low', 'no') returning id) insert into claim_test_ids select 'supplier_three', id from inserted;

with inserted as (
  insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, evidence_descriptors)
  values ((select id from claim_test_ids where name = 'claimant'), (select id from claim_test_ids where name = 'supplier_one'), statement_timestamp() + interval '30 days', 'synthetic_claim_reason', 'v1', '{"display_name":"Synthetic Claimant"}'::jsonb, 'v1', 'synthetic_submission_fingerprint', 'v1', '[{"kind":"business_document"}]'::jsonb) returning id
) insert into claim_test_ids select 'submitted', id from inserted;
select is((select status from public.supplier_ownership_claims where id = (select id from claim_test_ids where name = 'submitted')), 'submitted', 'valid Claim defaults to submitted');
select ok((select substring(id::text from 15 for 1) = '4' from public.supplier_ownership_claims where id = (select id from claim_test_ids where name = 'submitted')), 'valid Claim receives UUIDv4 identity');
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version) values ((select id from claim_test_ids where name = 'claimant'), (select id from claim_test_ids where name = 'supplier_one'), statement_timestamp() + interval '30 days', 'duplicate', 'v1', '{}'::jsonb, 'v1', 'duplicate_fingerprint', 'v1') $$, null, 'same claimant and Supplier cannot have two active Claims');
select lives_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version) values ((select id from claim_test_ids where name = 'other_claimant'), (select id from claim_test_ids where name = 'supplier_one'), statement_timestamp() + interval '30 days', 'other_claimant', 'v1', '{}'::jsonb, 'v1', 'other_fingerprint', 'v1') $$, 'different claimants may concurrently claim the same Supplier');
select lives_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version) values ((select id from claim_test_ids where name = 'claimant'), (select id from claim_test_ids where name = 'supplier_two'), statement_timestamp() + interval '30 days', 'other_supplier', 'v1', '{}'::jsonb, 'v1', 'other_supplier_fingerprint', 'v1') $$, 'one claimant may have active Claims for different Suppliers');
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, status, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version) values ((select id from claim_test_ids where name = 'claimant'), gen_random_uuid(), 'invalid', statement_timestamp() + interval '30 days', 'invalid_status', 'v1', '{}'::jsonb, 'v1', 'invalid_status_fingerprint', 'v1') $$, null, 'unapproved Claim lifecycle status is rejected');
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, status, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version) values ((select id from claim_test_ids where name = 'claimant'), gen_random_uuid(), 'under_review', statement_timestamp() + interval '30 days', 'missing_assignment', 'v1', '{}'::jsonb, 'v1', 'missing_assignment_fingerprint', 'v1') $$, null, 'under_review requires the durable reviewer assignment shape');
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, evidence_descriptors) values ((select id from claim_test_ids where name = 'claimant'), gen_random_uuid(), statement_timestamp() + interval '30 days', 'too_many_evidence', 'v1', '{}'::jsonb, 'v1', 'too_many_evidence_fingerprint', 'v1', '[{}, {}, {}, {}]'::jsonb) $$, null, 'more than three evidence descriptors are rejected');
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, evidence_descriptors) values ((select id from claim_test_ids where name = 'claimant'), gen_random_uuid(), statement_timestamp() + interval '30 days', 'scalar_evidence', 'v1', '{}'::jsonb, 'v1', 'scalar_evidence_fingerprint', 'v1', '["not_a_descriptor"]'::jsonb) $$, null, 'evidence descriptors must be JSON objects');
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version) values ((select id from claim_test_ids where name = 'claimant'), gen_random_uuid(), statement_timestamp() - interval '1 second', 'invalid_expiry', 'v1', '{}'::jsonb, 'v1', 'invalid_expiry_fingerprint', 'v1') $$, null, 'expiry cannot precede trusted submission');

select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, status, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, reviewer_user_profile_id, reviewer_assignment_version, reviewer_assigned_at, reviewer_assigned_by_user_profile_id, reviewer_assignment_source_code, reviewer_assignment_policy_version) values ((select id from claim_test_ids where name = 'claimant'), gen_random_uuid(), 'under_review', statement_timestamp() + interval '30 days', 'claimant_reviewer_conflict', 'v1', '{}'::jsonb, 'v1', 'claimant_reviewer_fingerprint', 'v1', (select id from claim_test_ids where name = 'claimant'), 1, statement_timestamp(), (select id from claim_test_ids where name = 'assigner'), 'claim_assignment', 'v1') $$, null, 'claimant cannot be their own assigned reviewer');
with inserted as (insert into public.supplier_ownerships (supplier_profile_id, controller_user_profile_id, establishment_source_type, establishment_reason_code, established_by_user_profile_id) values ((select id from claim_test_ids where name = 'supplier_three'), (select id from claim_test_ids where name = 'claimant'), 'claim_approval', 'synthetic_claim_approval', (select id from claim_test_ids where name = 'reviewer')) returning id) insert into claim_test_ids select 'ownership_result', id from inserted;
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, status, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, reviewer_user_profile_id, reviewer_assignment_version, reviewer_assigned_at, reviewer_assigned_by_user_profile_id, reviewer_assignment_source_code, reviewer_assignment_policy_version, decided_by_user_profile_id, decided_at, decision_reason_code, evidence_verification_method_code, evidence_verification_version, evidence_verification_outcome_code, decision_authorization_policy_version) values ((select id from claim_test_ids where name = 'claimant'), (select id from claim_test_ids where name = 'supplier_three'), 'approved', statement_timestamp() + interval '30 days', 'missing_result', 'v1', '{}'::jsonb, 'v1', 'missing_result_fingerprint', 'v1', (select id from claim_test_ids where name = 'reviewer'), 1, statement_timestamp(), (select id from claim_test_ids where name = 'assigner'), 'claim_assignment', 'v1', (select id from claim_test_ids where name = 'reviewer'), statement_timestamp(), 'approved', 'manual_review', 'v1', 'verified', 'v1') $$, null, 'approved Claim requires an ownership-result reference');
with inserted as (
  insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, status, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, reviewer_user_profile_id, reviewer_assignment_version, reviewer_assigned_at, reviewer_assigned_by_user_profile_id, reviewer_assignment_source_code, reviewer_assignment_policy_version, decided_by_user_profile_id, decided_at, decision_reason_code, evidence_verification_method_code, evidence_verification_version, evidence_verification_outcome_code, decision_authorization_policy_version, resulting_supplier_ownership_id)
  values ((select id from claim_test_ids where name = 'claimant'), (select id from claim_test_ids where name = 'supplier_three'), 'approved', statement_timestamp() + interval '30 days', 'approved_claim', 'v1', '{}'::jsonb, 'v1', 'approved_fingerprint', 'v1', (select id from claim_test_ids where name = 'reviewer'), 1, statement_timestamp(), (select id from claim_test_ids where name = 'assigner'), 'claim_assignment', 'v1', (select id from claim_test_ids where name = 'reviewer'), statement_timestamp(), 'approved', 'manual_review', 'v1', 'verified', 'v1', (select id from claim_test_ids where name = 'ownership_result')) returning id
) insert into claim_test_ids select 'approved', id from inserted;
select ok((select resulting_supplier_ownership_id is not null from public.supplier_ownership_claims where id = (select id from claim_test_ids where name = 'approved')), 'approved Claim can retain the unique ownership provenance reference');
select throws_ok($$ insert into public.supplier_ownership_claims (claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, resulting_supplier_ownership_id) values ((select id from claim_test_ids where name = 'other_claimant'), (select id from claim_test_ids where name = 'supplier_two'), statement_timestamp() + interval '30 days', 'result_on_submitted', 'v1', '{}'::jsonb, 'v1', 'result_on_submitted_fingerprint', 'v1', (select id from claim_test_ids where name = 'ownership_result')) $$, null, 'non-approved Claim cannot claim an ownership result');
select throws_ok($$ insert into public.supplier_ownership_claims (id, claimant_user_profile_id, supplier_profile_id, expires_at, submitted_reason, claimant_snapshot_schema_version, claimant_snapshot, submission_fingerprint_version, submission_fingerprint, evidence_schema_version, prior_claim_id) values ('11111111-1111-4111-8111-111111111111', (select id from claim_test_ids where name = 'other_claimant'), gen_random_uuid(), statement_timestamp() + interval '30 days', 'self_prior', 'v1', '{}'::jsonb, 'v1', 'self_prior_fingerprint', 'v1', '11111111-1111-4111-8111-111111111111') $$, null, 'Claim cannot be its own prior Claim');
select throws_ok($$ delete from public.user_profiles where id = (select id from claim_test_ids where name = 'claimant') $$, null, 'Claim claimant FK uses ON DELETE RESTRICT');
select throws_ok($$ delete from public.supplier_profiles where id = (select id from claim_test_ids where name = 'supplier_one') $$, null, 'Claim Supplier FK uses ON DELETE RESTRICT');

select * from finish();

rollback;
