import type { SupplierOwnershipErrorKey } from "../utils/supplierOwnershipUi";
import type { SupplierOwnershipClaimStatus, SupplierOwnershipEvidenceType } from "../types/domain";

const en = {
  direction: "ltr" as const,
  claim: {
    eyebrow: "Supplier ownership",
    title: "Claim an existing company profile",
    description: "Find your approved company profile and send evidence for a secure ownership review.",
    linkedTitle: "Your company profile is linked",
    linkedBody: "The canonical account and company ownership records are connected. You can continue to the Supplier workspace.",
    openWorkspace: "Open Supplier workspace",
    ineligibleTitle: "This account cannot submit a claim",
    ineligibleBody: "Claims require a verified, approved, active Supplier contributor account that is not already linked.",
    verifyTitle: "Verify your email first",
    verifyBody: "Complete email verification before searching for or claiming a company profile.",
    verifyAction: "Verify email",
    pendingTitle: "Your claim is pending review",
    pendingBody: "You can review the submitted evidence or withdraw the claim before an Admin decision.",
    searchTitle: "Find your company",
    searchDescription: "Enter at least two characters. Results contain only approved, unowned company profiles.",
    searchLabel: "Company name",
    searchAction: "Search",
    searchPlaceholder: "Start typing the approved company name",
    searchBusy: "Searching approved companies…",
    searchHint: "Search is limited to protect the directory. Use the most specific company name available.",
    searchEmpty: "No eligible company found",
    searchEmptyBody: "If your company is not listed, use the existing Add Supplier workflow instead of creating a claim.",
    addSupplier: "Add a company",
    selectedTitle: "Selected company",
    changeSelection: "Choose another company",
    location: "Location",
    categories: "Categories",
    website: "Website domain",
    select: "Select company",
    formTitle: "Ownership evidence",
    formDescription: "Explain your authority and provide references an Admin can review. File uploads are not supported.",
    claimReason: "Claim reason",
    claimReasonHint: "20–1,200 characters describing why you are authorized to manage this company profile.",
    evidenceType: "Evidence type",
    evidenceSummary: "Evidence summary",
    evidenceSummaryHint: "20–1,600 characters. Do not include passwords, tokens, or unnecessary personal data.",
    referenceLinks: "HTTPS reference links",
    referenceLinksHint: "Optional. Up to three public HTTPS links; no uploads or embedded content.",
    referenceLink: "Reference link {{index}}",
    submit: "Submit ownership claim",
    submitting: "Submitting claim…",
    submitted: "Your ownership claim was submitted for Admin review.",
    history: "Claim history",
    historyAction: "View claim history",
    noHistory: "No ownership claims yet",
    noHistoryBody: "When you submit a claim, its current status and permitted decision details will appear here.",
    withdraw: "Withdraw pending claim",
    withdrawTitle: "Withdraw this ownership claim?",
    withdrawBody: "The pending review will end and no company ownership will be granted. You may start a new claim only if the backend still permits it.",
    withdrawing: "Withdrawing…",
    withdrawn: "The pending ownership claim was withdrawn.",
    cancel: "Cancel",
    confirm: "Confirm",
    created: "Created",
    expires: "Expires",
    reviewed: "Reviewed",
    adminNotes: "Admin notes",
    evidence: "Evidence",
    claimReference: "Claim reference",
    backToClaim: "Back to claim",
    loadMore: "Load more",
    loading: "Loading ownership claims…",
    retry: "Retry",
  },
  admin: {
    eyebrow: "Supplier operations",
    queueTitle: "Ownership claims review queue",
    queueDescription: "Review bounded, indexed claim results and use trusted callable decisions only.",
    statusFilter: "Claim status",
    newestFirst: "Newest first",
    noClaims: "No claims in this state",
    noClaimsBody: "Choose another supported status or return when new claims arrive.",
    claimant: "Claimant",
    company: "Company profile",
    created: "Created",
    expires: "Expires",
    review: "Review claim",
    detailTitle: "Supplier ownership claim",
    detailDescription: "Review claimant evidence and the selected company before making an audited decision.",
    claimantSnapshot: "Claimant snapshot",
    selectedProfile: "Selected Supplier profile",
    decisionHistory: "Decision record",
    eventReference: "Immutable event reference",
    conflictingClaims: "Other pending claims for this company",
    noConflicts: "No other pending claims were found in the bounded query.",
    approvalTitle: "Approve this ownership claim?",
    approvalBody: "Approval links the account and Supplier profile, enables the approved Supplier for RFQ reception under backend rules, supersedes applicable conflicting claims, and creates an audited ownership decision.",
    rejectionTitle: "Reject this ownership claim?",
    rejectionBody: "Rejection grants no ownership and releases the claimant lock through the trusted backend.",
    adminNotes: "Admin notes",
    adminNotesHint: "Up to 1,000 characters. Rejection requires a concise reason.",
    approve: "Approve claim",
    reject: "Reject claim",
    approving: "Approving…",
    rejecting: "Rejecting…",
    approved: "The claim was approved and the canonical ownership link was created.",
    rejected: "The claim was rejected without granting ownership.",
    terminal: "This claim is complete and is read-only.",
    expired: "This claim has expired. Refresh the queue before reviewing another claim.",
    refresh: "Refresh claim",
    backToQueue: "Back to queue",
    profileUnavailable: "The selected Supplier profile is unavailable or no longer readable.",
    loadMore: "Load more",
    loading: "Loading ownership claims…",
  },
  statuses: {
    pending_review: "Pending review",
    approved: "Approved",
    rejected: "Rejected",
    withdrawn: "Withdrawn",
    expired: "Expired",
    superseded: "Superseded",
  } satisfies Record<SupplierOwnershipClaimStatus, string>,
  evidenceTypes: {
    company_domain_email: "Company-domain email",
    company_website: "Company website",
    commercial_registration: "Commercial registration",
    authorization_letter: "Authorization letter",
    other: "Other evidence",
  } satisfies Record<SupplierOwnershipEvidenceType, string>,
  validation: {
    required: "This field is required.",
    claimReasonLength: "Enter between 20 and 1,200 characters.",
    evidenceSummaryLength: "Enter between 20 and 1,600 characters.",
    tooManyLinks: "Provide no more than three reference links.",
    unsafeLink: "Each reference must be a public HTTPS link without credentials or a non-standard port.",
    duplicateLink: "Remove duplicate reference links.",
    selectCompany: "Select an eligible company from the current search results.",
    adminNotesRequired: "Add a concise rejection reason.",
  },
  errors: {
    feature_disabled: "Supplier profile claims are not available.",
    authentication_required: "Sign in to continue.",
    email_verification_required: "Verify your email and refresh your account before continuing.",
    ineligible_account: "This account is not currently eligible to submit or manage a claim.",
    already_linked: "This Supplier account is already linked to a company profile.",
    active_claim_exists: "This account already has an active ownership claim.",
    supplier_already_owned: "This company profile is already owned and cannot be claimed.",
    claim_expired: "This ownership claim has expired. Refresh to see its current state.",
    stale_claim: "The claim changed or its lock is no longer current. The latest state has been loaded.",
    claim_conflict: "The claim conflicts with a newer ownership decision. The latest state has been loaded.",
    rate_limited: "Too many claim searches or conflicts were requested. Wait one minute before trying again.",
    unsafe_evidence: "One or more evidence links are unsafe or malformed.",
    invalid_input: "Review the highlighted fields and submit valid claim information.",
    permission_denied: "You do not have permission to perform this ownership action.",
    not_found: "The ownership claim or Supplier profile was not found.",
    unavailable: "The service is temporarily unavailable. Your retry will reuse the same safe submission attempt.",
    internal_error: "The ownership request could not be completed. Try again later.",
  } satisfies Record<SupplierOwnershipErrorKey, string>,
};

const ar = {
  direction: "rtl",
  claim: {
    eyebrow: "ملكية ملف المجهز",
    title: "المطالبة بملف شركة قائم",
    description: "ابحث عن ملف شركتك المعتمد وأرسل أدلة الملكية لمراجعتها بصورة آمنة.",
    linkedTitle: "تم ربط ملف شركتك بالحساب",
    linkedBody: "سجلات الحساب وملكية الشركة الرسمية مترابطة الآن. يمكنك المتابعة إلى مساحة عمل المجهز.",
    openWorkspace: "فتح مساحة عمل المجهز",
    ineligibleTitle: "هذا الحساب غير مؤهل لإرسال مطالبة",
    ineligibleBody: "تتطلب المطالبة حساب مجهز مساهماً وموثق البريد ومعتمداً وفعالاً وغير مرتبط مسبقاً.",
    verifyTitle: "وثّق بريدك الإلكتروني أولاً",
    verifyBody: "أكمل توثيق البريد الإلكتروني قبل البحث عن ملف شركة أو المطالبة به.",
    verifyAction: "توثيق البريد",
    pendingTitle: "مطالبتك بانتظار المراجعة",
    pendingBody: "يمكنك مراجعة الأدلة المرسلة أو سحب المطالبة قبل صدور قرار الإدارة.",
    searchTitle: "ابحث عن شركتك",
    searchDescription: "أدخل حرفين على الأقل. تظهر النتائج ملفات الشركات المعتمدة وغير المملوكة فقط.",
    searchLabel: "اسم الشركة",
    searchAction: "بحث",
    searchPlaceholder: "ابدأ بكتابة اسم الشركة المعتمد",
    searchBusy: "جارٍ البحث في الشركات المعتمدة…",
    searchHint: "البحث محدود لحماية الدليل. استخدم الاسم الأكثر دقة للشركة.",
    searchEmpty: "لم يتم العثور على شركة مؤهلة",
    searchEmptyBody: "إذا لم تكن شركتك مدرجة فاستخدم مسار إضافة مجهز الحالي بدلاً من إنشاء مطالبة.",
    addSupplier: "إضافة شركة",
    selectedTitle: "الشركة المحددة",
    changeSelection: "اختيار شركة أخرى",
    location: "الموقع",
    categories: "التصنيفات",
    website: "نطاق الموقع الإلكتروني",
    select: "اختيار الشركة",
    formTitle: "أدلة الملكية",
    formDescription: "وضّح صلاحيتك وقدّم مراجع يمكن للإدارة مراجعتها. رفع الملفات غير مدعوم.",
    claimReason: "سبب المطالبة",
    claimReasonHint: "من 20 إلى 1,200 حرف توضح سبب صلاحيتك لإدارة ملف الشركة.",
    evidenceType: "نوع الدليل",
    evidenceSummary: "ملخص الأدلة",
    evidenceSummaryHint: "من 20 إلى 1,600 حرف. لا تذكر كلمات مرور أو رموز وصول أو بيانات شخصية غير ضرورية.",
    referenceLinks: "روابط مرجعية آمنة HTTPS",
    referenceLinksHint: "اختيارية، وبحد أقصى ثلاثة روابط عامة. لا يوجد رفع ملفات أو محتوى مضمّن.",
    referenceLink: "الرابط المرجعي {{index}}",
    submit: "إرسال مطالبة الملكية",
    submitting: "جارٍ إرسال المطالبة…",
    submitted: "تم إرسال مطالبة الملكية لمراجعة الإدارة.",
    history: "سجل المطالبات",
    historyAction: "عرض سجل المطالبات",
    noHistory: "لا توجد مطالبات ملكية بعد",
    noHistoryBody: "بعد إرسال المطالبة ستظهر حالتها الحالية وتفاصيل القرار المسموح بها هنا.",
    withdraw: "سحب المطالبة المعلقة",
    withdrawTitle: "هل تريد سحب مطالبة الملكية؟",
    withdrawBody: "ستنتهي المراجعة المعلقة ولن تُمنح ملكية للشركة. يمكنك بدء مطالبة جديدة فقط إذا سمح النظام الخلفي بذلك.",
    withdrawing: "جارٍ السحب…",
    withdrawn: "تم سحب مطالبة الملكية المعلقة.",
    cancel: "إلغاء",
    confirm: "تأكيد",
    created: "تاريخ الإنشاء",
    expires: "تاريخ الانتهاء",
    reviewed: "تاريخ المراجعة",
    adminNotes: "ملاحظات الإدارة",
    evidence: "الأدلة",
    claimReference: "مرجع المطالبة",
    backToClaim: "العودة إلى المطالبة",
    loadMore: "تحميل المزيد",
    loading: "جارٍ تحميل مطالبات الملكية…",
    retry: "إعادة المحاولة",
  },
  admin: {
    eyebrow: "عمليات المجهزين",
    queueTitle: "قائمة مراجعة مطالبات الملكية",
    queueDescription: "راجع نتائج محدودة ومفهرسة، واتخذ القرارات عبر الوظائف الموثوقة فقط.",
    statusFilter: "حالة المطالبة",
    newestFirst: "الأحدث أولاً",
    noClaims: "لا توجد مطالبات بهذه الحالة",
    noClaimsBody: "اختر حالة أخرى مدعومة أو عد عند وصول مطالبات جديدة.",
    claimant: "صاحب المطالبة",
    company: "ملف الشركة",
    created: "تاريخ الإنشاء",
    expires: "تاريخ الانتهاء",
    review: "مراجعة المطالبة",
    detailTitle: "مطالبة ملكية ملف مجهز",
    detailDescription: "راجع أدلة صاحب المطالبة والشركة المحددة قبل اتخاذ قرار مدقق.",
    claimantSnapshot: "بيانات صاحب المطالبة وقت الإرسال",
    selectedProfile: "ملف المجهز المحدد",
    decisionHistory: "سجل القرار",
    eventReference: "مرجع الحدث الثابت",
    conflictingClaims: "مطالبات معلقة أخرى لهذه الشركة",
    noConflicts: "لم تظهر مطالبات معلقة أخرى ضمن الاستعلام المحدود.",
    approvalTitle: "هل توافق على مطالبة الملكية؟",
    approvalBody: "تربط الموافقة الحساب بملف المجهز، وتفعّل استقبال طلبات الأسعار وفق قواعد النظام الخلفي، وتستبدل المطالبات المتعارضة عند انطباق ذلك، وتنشئ قرار ملكية مدققاً.",
    rejectionTitle: "هل ترفض مطالبة الملكية؟",
    rejectionBody: "لا يمنح الرفض أي ملكية ويحرر قفل صاحب المطالبة عبر النظام الخلفي الموثوق.",
    adminNotes: "ملاحظات الإدارة",
    adminNotesHint: "بحد أقصى 1,000 حرف. يتطلب الرفض سبباً موجزاً.",
    approve: "الموافقة على المطالبة",
    reject: "رفض المطالبة",
    approving: "جارٍ تنفيذ الموافقة…",
    rejecting: "جارٍ تنفيذ الرفض…",
    approved: "تمت الموافقة وإنشاء رابط الملكية الرسمي.",
    rejected: "تم رفض المطالبة من دون منح ملكية.",
    terminal: "اكتملت هذه المطالبة وأصبحت للقراءة فقط.",
    expired: "انتهت صلاحية هذه المطالبة. حدّث القائمة قبل مراجعة مطالبة أخرى.",
    refresh: "تحديث المطالبة",
    backToQueue: "العودة إلى القائمة",
    profileUnavailable: "ملف المجهز المحدد غير متاح أو لم يعد قابلاً للقراءة.",
    loadMore: "تحميل المزيد",
    loading: "جارٍ تحميل مطالبات الملكية…",
  },
  statuses: {
    pending_review: "بانتظار المراجعة",
    approved: "موافق عليها",
    rejected: "مرفوضة",
    withdrawn: "مسحوبة",
    expired: "منتهية",
    superseded: "مستبدلة",
  },
  evidenceTypes: {
    company_domain_email: "بريد تابع لنطاق الشركة",
    company_website: "موقع الشركة الإلكتروني",
    commercial_registration: "التسجيل التجاري",
    authorization_letter: "كتاب تخويل",
    other: "دليل آخر",
  },
  validation: {
    required: "هذا الحقل مطلوب.",
    claimReasonLength: "أدخل نصاً بين 20 و1,200 حرف.",
    evidenceSummaryLength: "أدخل نصاً بين 20 و1,600 حرف.",
    tooManyLinks: "لا تُدخل أكثر من ثلاثة روابط مرجعية.",
    unsafeLink: "يجب أن يكون كل مرجع رابط HTTPS عاماً بلا بيانات دخول أو منفذ غير قياسي.",
    duplicateLink: "احذف الروابط المرجعية المكررة.",
    selectCompany: "اختر شركة مؤهلة من نتائج البحث الحالية.",
    adminNotesRequired: "أضف سبباً موجزاً للرفض.",
  },
  errors: {
    feature_disabled: "مطالبات ملفات المجهزين غير متاحة حالياً.",
    authentication_required: "سجّل الدخول للمتابعة.",
    email_verification_required: "وثّق بريدك الإلكتروني ثم حدّث حسابك للمتابعة.",
    ineligible_account: "هذا الحساب غير مؤهل حالياً لإرسال مطالبة أو إدارتها.",
    already_linked: "حساب المجهز هذا مرتبط مسبقاً بملف شركة.",
    active_claim_exists: "لدى هذا الحساب مطالبة ملكية فعالة بالفعل.",
    supplier_already_owned: "ملف الشركة مملوك بالفعل ولا يمكن المطالبة به.",
    claim_expired: "انتهت صلاحية مطالبة الملكية. حدّث الصفحة لعرض حالتها الحالية.",
    stale_claim: "تغيرت المطالبة أو لم يعد قفلها سارياً. تم تحميل أحدث حالة.",
    claim_conflict: "تتعارض المطالبة مع قرار ملكية أحدث. تم تحميل أحدث حالة.",
    rate_limited: "تم إجراء عدد كبير من عمليات البحث أو التعارضات. انتظر دقيقة ثم أعد المحاولة.",
    unsafe_evidence: "رابط دليل واحد أو أكثر غير آمن أو غير صالح.",
    invalid_input: "راجع الحقول المحددة وأرسل معلومات مطالبة صحيحة.",
    permission_denied: "ليست لديك صلاحية لتنفيذ إجراء الملكية هذا.",
    not_found: "لم يتم العثور على مطالبة الملكية أو ملف المجهز.",
    unavailable: "الخدمة غير متاحة مؤقتاً. ستستخدم إعادة المحاولة محاولة الإرسال الآمنة نفسها.",
    internal_error: "تعذر إكمال طلب الملكية. حاول لاحقاً.",
  },
};

export const supplierOwnershipCopy = { en, ar };
export type SupplierOwnershipLocale = keyof typeof supplierOwnershipCopy;