[CmdletBinding()]
param([string]$PostgresImage='supabase/postgres:17.6.1.064')
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$name="mujahiz-reject-race-$PID-$([guid]::NewGuid().ToString('N').Substring(0,8))"
$started=$false;$checks=[Collections.Generic.List[string]]::new();$sw=[Diagnostics.Stopwatch]::StartNew()
function Assert([bool]$ok,[string]$message){if(-not $ok){throw "Assertion failed: $message"};$script:checks.Add($message)}
function Q([string]$sql,[string]$label,[switch]$allow){
 $a=@('exec',$name,'psql','--no-psqlrc','--set=ON_ERROR_STOP=1','--set=VERBOSITY=verbose','-U','postgres','-d','postgres','-qAt','-P','footer=off','-c',$sql)
 $old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=@(& docker @a 2>&1|ForEach-Object{$_.ToString()});$code=$LASTEXITCODE;$ErrorActionPreference=$old
 if($code -ne 0 -and -not $allow){throw "$label failed. $($o -join [Environment]::NewLine)"}
 [pscustomobject]@{ExitCode=$code;Output=$o;Text=$o -join [Environment]::NewLine}
}
function J($call,[string]$label){if($call.ExitCode){throw "$label failed. $($call.Text)"};$line=@($call.Output|Where-Object{$_ -match '^\{'}|Select-Object -Last 1);if($line.Count-ne 1){throw "$label returned no JSON"};$line[0]|ConvertFrom-Json}
function RuntimeSql([string]$principal,[string]$body){"set role mujahiz_claim_runtime;begin;select claim_security.establish_claim_runtime_context('$principal');select set_config('mujahiz.claim.hmac_key',repeat('k',32),true);$body commit;"}
function Reserve([string]$p,[string]$k,[string]$c,[string]$reason='supplier_mismatch',[string]$outcome='verified',[string]$ref='race-ref'){
 Q (RuntimeSql $p "select row_to_json(x)::text from supplier_claim.reject('$k','$c',2,1,'$reason','manual_review','claim_evidence_review_v1','$outcome','$ref',null)x;") reserve
}
function Reject([string]$p,[string]$k,[string]$c,[string]$f,[string]$reason='supplier_mismatch',[string]$outcome='verified',[string]$ref='race-ref'){
 RuntimeSql $p "select row_to_json(x)::text from supplier_claim._execute_reject('$k','$c',2,1,'$reason','manual_review','claim_evidence_review_v1','$outcome','$ref',null,'$f')x;"
}
function WReserve([string]$p,[string]$k,[string]$c){Q (RuntimeSql $p "select row_to_json(x)::text from supplier_claim.reserve_withdraw('$k','$c',2)x;") withdraw}
function Withdraw([string]$p,[string]$k,[string]$c,[string]$f){RuntimeSql $p "select row_to_json(x)::text from supplier_claim.withdraw('$k','$c',2,null,'$f')x;"}
function Block([string]$s,[int]$seconds=3){"begin;select pg_advisory_xact_lock(claim_security.claim_supplier_lock_key_v1('$s'));select pg_sleep($seconds);commit;"}
function Race([string]$one,[string]$two,[string]$block){
 $docker=(Get-Command docker).Source;$run={param($d,$n,$s);$a=@('exec',$n,'psql','--no-psqlrc','--set=ON_ERROR_STOP=1','--set=VERBOSITY=verbose','-U','postgres','-d','postgres','-qAt','-P','footer=off','-c',$s);$o=@(& $d @a 2>&1|ForEach-Object{$_.ToString()});[pscustomobject]@{ExitCode=$LASTEXITCODE;Output=$o;Text=$o -join [Environment]::NewLine}}
 $b=Start-Job $run -ArgumentList $docker,$name,$block;Start-Sleep -Milliseconds 500;$j1=Start-Job $run -ArgumentList $docker,$name,$one;$j2=Start-Job $run -ArgumentList $docker,$name,$two
 try{Wait-Job @($j1,$j2) -Timeout 30|Out-Null;Wait-Job $b -Timeout 30|Out-Null;if($j1.State-ne'Completed'-or$j2.State-ne'Completed'-or$b.State-ne'Completed'){throw 'race timeout'};@($j1,$j2|ForEach-Object{Receive-Job $_})}finally{Remove-Job @($j1,$j2,$b) -Force -ErrorAction SilentlyContinue}
}
try{
 $mount="type=bind,source=$root,target=/workspace,readonly";docker run -d --rm --name $name --mount $mount -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres $PostgresImage|Out-Null;if($LASTEXITCODE){throw 'container start failed'};$started=$true
 $ready=$false;1..60|ForEach-Object{if(-not$ready){docker exec $name pg_isready -U postgres -d postgres*>$null;$db=$LASTEXITCODE-eq 0;docker exec $name sh -c "ps -eo args | grep '[m]igrate.sh' > /dev/null"*>$null;if($db-and$LASTEXITCODE-ne 0){$ready=$true}else{Start-Sleep -Milliseconds 500}}};if(-not$ready){throw 'postgres not ready'}
 $boot="create schema if not exists extensions;create extension if not exists pgtap with schema extensions;do "+'$x$'+" begin if not exists(select 1 from pg_roles where rolname='anon')then create role anon nologin noinherit;end if;if not exists(select 1 from pg_roles where rolname='authenticated')then create role authenticated nologin noinherit;end if;if not exists(select 1 from pg_roles where rolname='service_role')then create role service_role nologin noinherit;end if;end "+'$x$'+";"
 Q $boot bootstrap|Out-Null
 Get-ChildItem (Join-Path $root 'supabase/migrations') -File -Filter '*.sql'|Sort-Object Name|ForEach-Object{$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=@(docker exec $name psql -X -v ON_ERROR_STOP=1 -q -U postgres -d postgres -f "/workspace/supabase/migrations/$($_.Name)" 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;if($code){throw "migration failed: $($_.Name) $o"}}
$source=[IO.File]::ReadAllText((Join-Path $root 'supabase/tests/reject_trusted_command.sql'));$a=$source.IndexOf('create function pg_temp.reject_id');$b=$source.IndexOf('-- Approved v1 reason/evidence matrix.');$helpers=$source.Substring($a,$b-$a).Replace('pg_temp.','public.');$temp=[IO.Path]::GetTempFileName();try{[IO.File]::WriteAllText($temp,$helpers,[Text.UTF8Encoding]::new($false));docker cp $temp ($name+':/tmp/reject-race-helpers.sql')|Out-Null;if($LASTEXITCODE){throw 'helper copy failed'};$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=@(docker exec $name psql -X -v ON_ERROR_STOP=1 -q -U postgres -d postgres -f /tmp/reject-race-helpers.sql 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;if($code){throw "helpers failed: $o"}}finally{Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue}
 $fixture=@("select public.seed_eligible_actor(1,'owner')","select public.seed_eligible_actor(2,'admin')","select public.seed_eligible_actor(3,'owner')","select public.seed_eligible_actor(4,'owner')","select public.seed_claimant(n) from generate_series(101,109)n","select public.seed_supplier(n) from generate_series(201,209)n")
 101..109|ForEach-Object{$fixture+="insert into internal.identity_provider_links(id,user_profile_id,provider_code,provider_subject,is_primary,link_status,identity_status,verification_status,provider_state_observed_at,provider_state_version,linked_at,verified_at,created_at)values(public.reject_id($_),public.reject_id($_),'firebase','race-claimant-$_',true,'linked','active','verified',statement_timestamp(),'firebase-provider-state-v1',statement_timestamp(),statement_timestamp(),statement_timestamp())"}
 1..9|ForEach-Object{$reviewer=if($_-eq 7){3}else{1};$fixture+="select public.seed_under_review_claim($(1000+$_),$(100+$_),$(200+$_),$reviewer,4)"}
 $fixture+='grant mujahiz_claim_runtime to postgres with set true';Q (($fixture-join';')+';') fixture|Out-Null
 $owner='b1000000-0000-4000-8000-000000000001';$admin='b1000000-0000-4000-8000-000000000002';$loss='b1000000-0000-4000-8000-000000000003'
 # same key / same request
 $c='b1000000-0000-4000-8000-000000001001';$s='b1000000-0000-4000-8000-000000000201';$k='claim-b0000000-0000-4000-8000-000000000101';$r=J (Reserve $owner $k $c) same;$x=Race (Reject $owner $k $c $r.execution_fence) (Reject $owner $k $c $r.execution_fence) (Block $s)
 Assert (@($x|Where-Object ExitCode -eq 0).Count-eq 1-and@($x|Where-Object ExitCode -ne 0)[0].Text-match'P5110.*retry_later') 'same key has one Phase-B winner'
 $re=J (Reserve $owner $k $c) replay;Assert ($re.reservation_outcome-eq'replay'-and$re.idempotent_replay) 'same key returns one logical replay'
 $st=(Q "select status||'/'||record_version||'/'||(select count(*)from internal.domain_events where aggregate_id='$c')||'/'||(select count(*)from internal.audit_logs where target_id='$c'and outcome_class='succeeded')from public.supplier_ownership_claims where id='$c';" state).Output|Where-Object{$_-match'^rejected/'}|Select-Object -Last 1;Assert ($st-eq'rejected/3/1/1') 'same key leaves one mutation audit and event'
 # same key / different reason
 $c='b1000000-0000-4000-8000-000000001002';$k='claim-b0000000-0000-4000-8000-000000000102';$r=J (Reserve $owner $k $c) reason;$bad=Q (Reject $owner $k $c $r.execution_fence 'claimant_ineligible') changed-reason -allow;Assert ($bad.ExitCode-ne 0-and$bad.Text-match'P5108.*idempotency_key_conflict') 'same key different reason has no wrong replay'
 # same key / different reference
 $c='b1000000-0000-4000-8000-000000001003';$k='claim-b0000000-0000-4000-8000-000000000103';$r=J (Reserve $owner $k $c -ref ref-one) reference;$bad=Q (Reject $owner $k $c $r.execution_fence -ref ref-two) changed-reference -allow;Assert ($bad.ExitCode-ne 0-and$bad.Text-match'P5108.*idempotency_key_conflict') 'same key different reference has no wrong replay'
 # different keys
 $c='b1000000-0000-4000-8000-000000001004';$s='b1000000-0000-4000-8000-000000000204';$k1='claim-b0000000-0000-4000-8000-000000000104';$k2='claim-b0000000-0000-4000-8000-000000000105';$a=J (Reserve $owner $k1 $c) dk1;$b=J (Reserve $owner $k2 $c) dk2;$x=Race (Reject $owner $k1 $c $a.execution_fence) (Reject $owner $k2 $c $b.execution_fence) (Block $s);Assert (@($x|Where-Object ExitCode -eq 0).Count-eq 1-and@($x|Where-Object ExitCode -ne 0)[0].Text-match'P5112.*claim_version_conflict') 'different keys commit one terminal reject'
 # reject vs withdraw
 $c='b1000000-0000-4000-8000-000000001005';$s='b1000000-0000-4000-8000-000000000205';$cl='b1000000-0000-4000-8000-000000000105';$rk='claim-b0000000-0000-4000-8000-000000000106';$wk='claim-b0000000-0000-4000-8000-000000000107';$r=J (Reserve $owner $rk $c) reject;$w=J (WReserve $cl $wk $c) withdraw;$x=Race (Reject $owner $rk $c $r.execution_fence) (Withdraw $cl $wk $c $w.execution_fence) (Block $s);Assert (@($x|Where-Object ExitCode -eq 0).Count-eq 1-and@($x|Where-Object ExitCode -ne 0)[0].Text-match'P5112.*claim_version_conflict') 'reject versus withdraw has one winner'
 $st=(Q "select status||'/'||record_version||'/'||(reviewer_user_profile_id='$owner')::text from public.supplier_ownership_claims where id='$c';" cross).Output|Where-Object{$_-match'^(rejected|withdrawn)/'}|Select-Object -Last 1;Assert ($st-in@('rejected/3/true','withdrawn/3/true')) 'reject withdraw preserves assignment'
 # expiry boundary
 $c='b1000000-0000-4000-8000-000000001006';$s='b1000000-0000-4000-8000-000000000206';Q "update public.supplier_ownership_claims set submitted_at=statement_timestamp()-interval '719 hours 59 minutes 57 seconds',created_at=statement_timestamp()-interval '719 hours 59 minutes 57 seconds',expires_at=statement_timestamp()+interval '3 seconds',reviewer_assigned_at=statement_timestamp()-interval '719 hours 58 minutes 57 seconds',updated_at=statement_timestamp()-interval '719 hours 58 minutes 57 seconds'where id='$c';" expiry|Out-Null;$k='claim-b0000000-0000-4000-8000-000000000108';$r=J (Reserve $owner $k $c) expiry-reserve;$x=Race (Reject $owner $k $c $r.execution_fence) 'select 1;' (Block $s 4);Assert ($x[0].ExitCode-ne 0-and$x[0].Text-match'P5114.*claim_expired') 'reject cannot commit at or after trusted expiry'
 # reviewer authority loss
 $c='b1000000-0000-4000-8000-000000001007';$k='claim-b0000000-0000-4000-8000-000000000109';$r=J (Reserve $loss $k $c) authority;$writer="begin;select pg_advisory_xact_lock(claim_security.claim_principal_lock_key_v1('$loss'));update internal.security_eligibility_assessments set assessment_result='deny',condition_type='security_hold',assessment_source_type='trusted_security_system'where user_profile_id='$loss';select pg_sleep(3);commit;";$x=Race (Reject $loss $k $c $r.execution_fence) 'select 1;' $writer;$result=J $x[0] authority-result;Assert ($result.outcome_code-eq'actor_not_authorized') 'authority loss is re-read after principal lock'
 # target conflict establishment
 $c='b1000000-0000-4000-8000-000000001008';$s='b1000000-0000-4000-8000-000000000208';$k='claim-b0000000-0000-4000-8000-000000000110';$r=J (Reserve $owner $k $c) conflict;$writer="begin;select pg_advisory_xact_lock(claim_security.claim_supplier_lock_key_v1('$s'));insert into public.supplier_ownership_claims(id,claimant_user_profile_id,supplier_profile_id,status,record_version,submitted_at,expires_at,submitted_reason,claimant_snapshot_schema_version,claimant_snapshot,submission_fingerprint_version,submission_fingerprint,evidence_schema_version,evidence_descriptors,created_at,updated_at)select 'b2000000-0000-4000-8000-000000000008','$owner','$s','submitted',1,t,t+interval '720 hours','race conflict','claimant_snapshot_v1','{}','claim_submit_v1',repeat('e',64),'claim_evidence_v1','[]',t,t from(select statement_timestamp()-interval '1 hour't)q;select pg_sleep(3);commit;";$x=Race (Reject $owner $k $c $r.execution_fence) 'select 1;' $writer;$result=J $x[0] conflict-result;Assert ($result.outcome_code-eq'reviewer_conflict') 'target conflict invalidates stale clear state'
 # approval-like ownership slot
 $c='b1000000-0000-4000-8000-000000001009';$s='b1000000-0000-4000-8000-000000000209';$k='claim-b0000000-0000-4000-8000-000000000111';$r=J (Reserve $owner $k $c) ownership;$writer="begin;select pg_advisory_xact_lock(claim_security.claim_supplier_lock_key_v1('$s'));insert into public.supplier_ownerships(id,supplier_profile_id,controller_user_profile_id,valid_from,establishment_source_type,establishment_reason_code,establishment_system_source)values('b2000000-0000-4000-8000-000000000009','$s','$admin',statement_timestamp()-interval '1 day','legacy_reconciliation','approval_like_race','reject_race');select pg_sleep(3);commit;";$x=Race (Reject $owner $k $c $r.execution_fence) 'select 1;' $writer;$result=J $x[0] ownership-result;Assert ($result.outcome_code-eq'rejected') 'approval-like ownership slot does not corrupt reject'
 $st=(Q "select status||'/'||record_version||'/'||(select count(*)from public.supplier_ownerships where supplier_profile_id='$s')from public.supplier_ownership_claims where id='$c';" ownership-state).Output|Where-Object{$_-match'^rejected/'}|Select-Object -Last 1;Assert ($st-eq'rejected/3/1') 'reject preserves independently established ownership'
 $global=(Q "select (select count(*)from internal.domain_events where event_type='supplier_ownership.claim_rejected')||'/'||(select count(*)from internal.audit_logs where action_code='supplier_claim.reject'and outcome_class='succeeded')||'/'||(select count(*)from internal.domain_events where event_type='supplier_ownership.claim_rejected'and(payload?'reviewer_user_profile_id'or payload?'evidence_digest'));" global).Output|Where-Object{$_-match'^\d+/\d+/\d+$'}|Select-Object -Last 1;Assert ($global-match'^([34])/\1/0$') 'global event and success-audit totals match without private leak'
 $sw.Stop();Write-Output ("Claim reject concurrency validation passed: {0} checks; nine true-session races; {1:n1}s elapsed."-f$checks.Count,$sw.Elapsed.TotalSeconds)
}finally{if($started){docker rm -f $name *> $null}}
